### ISSUE TITLE
error info.xml

### ISSUE THREAD

**Issue by grimlis** [trading-code/ninjatrader-freeorderflow#1]
the ninja script archive file does not contain an info.xml file or is currept.please chek the archive file <<<< error
[ninjatrader-freeorderflow-main.zip](https://github.com/trading-code/ninjatrader-freeorderflow/files/11357140/ninjatrader-freeorderflow-main.zip)

**Comment by roldaojr** [comment]
Unfortunately, the zip format from Github is not compatible. Check releases page for working file
